name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

 
env:
  app_name: ubuntu-latest
 
jobs:
  
  build:
    
    runs-on: windows-2022

    
    steps:
      - uses: actions/checkout@v3
      - name: Build

        run: g++ Source.cpp -o ${{env.app_name}}-${{runner.os}}


      - name: Upload Artefact
        uses: actions/upload-artifact@v3
        with:
          name: artefact_fol
          path: ${{env.app_name}}-${{ runner.os}}**
          
          
  telegram:
    needs: build 
        
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      
      #download
      - uses: actions/download-artifact@v3
        with:
          name: artefact_fol
          path: artifacts
          
      - name: Send to TG
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{secrets.TELEGRAM_TOKEN }}
          message: Present
          document: artifacts/**
        
        
        





