name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  app_name: app.exe

jobs:
  build:   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: g++ Source.cpp -o ${{env.app_name}}_${{runner.os}}


      - name: Upload Artefact
        uses: dowlaod-artifact@v3
        with:
          name: my-artefact
          path: ${{env.app_name}}-${{runner.os}}
          
          
  telegram:
    needs: build 
        
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/dowlaod-artifact@v3
        with:
          name: artifacts_folder
          path: artifacts
          
      - name: Send to TG
        uses: appleboy/telegram-action@main
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{secrets.TELEGRAM_TOKEN }}
          message: Present
          document: artifacts/**
        
        
        





